remote_theme: just-the-docs/just-the-docs

title: Text Complexity DE Challenge 2022
description: GermEval Shared Task
baseurl: "/text_complexity_challlenge" # the subpath of your site, e.g. /blog
url: "https://qulab.github.io/"

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/logo2.png"

